server:
  url: "https://ncei.noaa.gov"
  timeout: 30
  retries: 3
  secure_connection: true
  dap_type: "tabledap" #should be tabledap or griddap
datasets:
  name: "CRCP_ARMS_Cryptic_Reef_Diversity_Pacific"
  dataset_url: ""
  variables:
    - name: ["Region", "Island", "Count"] #these must be fully typed for tabledap variables
      dimensions: ["time", "lat", "lon"] #
      range:
        time: ["2016-06-01", "2017-06-20"]
        lat: [14.6, 18.4]
        lon: [-178.37, 166]
query:
  output_format: "csv" #outputformat can be any one of:  .csv, .htmlTable, .itx, .json, .jsonlCSV1, .jsonlCSV, .jsonlKVP, .mat, .nc, .nccsv, .tsv, or .xhtml
  chunk_size: 1000
  fetch_all: false
data_processing:
  remove_outliers: true
  interpolation_method: ""
  fill_value: "NaN"
  aggregation:
    method: "mean"
    time_window: "1D"
