server:
  url: "https://coastwatch.noaa.gov"
  timeout: 30
  retries: 3
  secure_connection: true
  dap_type: "griddap" #should be tabledap or griddap
datasets:
  name:  "noaacwNPPN20S3ASCIDINEOF2kmDaily"
  dataset_url: ""
  variables:
    - name: ["chlor_a"]
      dimensions: ["time", "lat", "lon"]
      range:
        time: ["2025-01-09", "2025-03-06"]
        lat: [-67.989586, -80.989586]
        long: [133.98961, 161.98961]
query:
  output_format: "nc"
  chunk_size: 1000
  fetch_all: false
data_processing:
  remove_outliers: true
  interpolation_method: ""
  fill_value: "NaN"
  aggregation:
    method: "mean"
    time_window: "1D"


