server:
  url: "https://coastwatch.noaa.gov/"
  timeout: 30
  retries: 3
  secure_connection: true
  dap_type: "gridded"
datasets:
  name: "noaacwNPPN20S3ASCIDINEOF2kmDaily"
  dataset_url: ""
  variables:
    - name: ["chlor_a"]
      dimensions: ["time", "lat", "lon"]
      range:
        time: ["2021-01-01", "2021-12-31"]
        lat: [0, 90]
        lon: [0, 179]
query:
  output_format: "nc"
  #outputformat can be any one of:  .csv, .htmlTable, .itx, .json, .jsonlCSV1, .jsonlCSV, .jsonlKVP, .mat, .nc, .nccsv, .tsv, or .xhtml
  chunk_size: 1000
  fetch_all: false
data_processing:
  remove_outliers: true
  interpolation_method: ""
  fill_value: "NaN"
  aggregation:
    method: "mean"
    time_window: "1D"
